title: Crux Ansata Oasis
author:
  name: Amber Peter
metadata:
    description: Crux Ansata Oasis is a local chapter of the Ordo Templi Orientis (OTO), located in the Valley of Denver, Colorado. As an Oasis we strive to provide the people within and without our valley with dramatic group rituals, classes and workshops, and a model of behavior expressing individual light, life, love, and liberty.

# Header customization
header:
  title: Crux Ansata Oasis
  description: <span>Ordo Templi Orientis</span> in the Valley of <span>Denver, Colorado</span><br><br>Do what thou wilt shall be the whole of the Law.<br>Love is the law, love under will.
copyright:
    - line: &copy; Copyright 2016 Crux Ansata
    - line: Design by <a title="Styleshout" href="http://www.styleshout.com/">Styleshout</a>
social:
- url: "https://www.facebook.com/CruxAnsataOTO/"
  icon: facebook
